name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop
      - master

jobs:
  ci-pipeline:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Run linter
        run: yarn lint

      - name: Run linters
        run: yarn test
